version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  target-branch: test
  ignore:
  - dependency-name: CsvHelper
    versions:
    - 27.0.1
  - dependency-name: Microsoft.Azure.WebJobs.Extensions.DurableTask
    versions:
    - 2.4.1
    - 2.4.2
    - 2.4.3
  - dependency-name: Newtonsoft.Json
    versions:
    - 13.0.1
  - dependency-name: Octokit
    versions:
    - 0.49.0
    - 0.50.0
  - dependency-name: nunit
    versions:
    - 3.13.0
    - 3.13.1
  - dependency-name: coverlet.collector
    versions:
    - 3.0.2
